### ISSUE TITLE
如何在单GPU下工作

### ISSUE THREAD

**Issue by rivercome** [gujingxiao/Lane-Segmentation-Solution-For-Baidu-PaddlePaddle-Autonomous-Driving-Competition#1]
1.请问在单GPU下运行你的代码时，fluid.Executor函数应该如何修改，以及其他文件是否需要变动。
2.请问所设计的俩个基于resnet网络的网络结构和各层层数？

**Comment by gujingxiao** [comment]
你好,

(1)如果要使用单GPU,请将train.py文件的104-110行注释掉
    # Parallel Executor to use multi-GPUs
    exec_strategy = fluid.ExecutionStrategy()
    exec_strategy.allow_op_delay = True
    build_strategy = fluid.BuildStrategy()
    build_strategy.reduce_strategy = fluid.BuildStrategy.ReduceStrategy.Reduce
    train_exe = fluid.ParallelExecutor(use_cuda=True, loss_name=reduced_loss.name,
build_strategy=build_strategy, exec_strategy=exec_strategy)

并将118行的train_exe改为exe.

(2)在设计两个网络时,我并未严格使用类似resnet34或者50这样的层数,而仅是使用了残差结构,并且做了一定的变化;所以我使用的是基于残差结构的Unet网络.如果感兴趣的话,可以阅读 MultiResUNet: Rethinking the unet architecture for multimodel biomedical image segmentation
