### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by kaishijeng** [gujingxiao/Lane-Segmentation-Solution-For-Baidu-PaddlePaddle-Autonomous-Driving-Competition#10]
Can you share your pretrained model?

Thanks,

**Comment by gujingxiao** [comment]
Hi, please go to the latest release to download the modified deeplab pretrained model. The other two unet models are pretty large so I don't attach them here. Recently, I notice that there is a competition held by Baidu very similar to this solution. To make it fair enough, I may not upload all models for this solution. Sorry about that.

**Comment by kaishijeng** [comment]
>>lease go to the latest release to download the modified deeplab pretrained model. 
I don't see your latest release with the pretrained model in the master branch of this repository

Thanks,

**Comment by kaishijeng** [comment]
Found it

Thanks,
