### ISSUE TITLE
怎么用双卡

### ISSUE THREAD

**Issue by hanhaixingxing** [gujingxiao/Lane-Segmentation-Solution-For-Baidu-PaddlePaddle-Autonomous-Driving-Competition#11]
您好，两个Tesla V100 怎么一起使用

**Comment by gujingxiao** [comment]
你好，代码里面直接的配置就是多卡训练，直接使用就行。如果用单卡的话，需要把parallelExecutoer那里改成普通的executor，或者使用最新的paddle api来自适应

**Comment by hanhaixingxing** [comment]
多谢🙏




                                                       杨丽芳            
手机号 188-1310-5394
在2020年09月16日 15:45，seigato 写道：

你好，代码里面直接的配置就是多卡训练，直接使用就行。如果用单卡的话，需要把parallelExecutoer那里改成普通的executor，或者使用最新的paddle api来自适应
