### ISSUE TITLE
是否有方法能解决reshape过程中的位移

### ISSUE THREAD

**Issue by youqingxiaozhua** [gujingxiao/Lane-Segmentation-Solution-For-Baidu-PaddlePaddle-Autonomous-Driving-Competition#13]
类似于您说的夺冠关键，最开始使用最近邻来reshape，之后使用双线性差值会导致位移，请问除了手动调整外，有什么合适的方法来解决这个问题吗？

**Comment by gujingxiao** [comment]
> 类似于您说的夺冠关键，最开始使用最近邻来reshape，之后使用双线性差值会导致位移，请问除了手动调整外，有什么合适的方法来解决这个问题吗？

你好，造成位移的一个主要原因是缩放都不是整数倍，然后缩小采用最邻近，放大采用双线性导致的。如果你这边训练的缩放操作都遵从整数倍，这个问题就不存在了。可以尝试一下。
