### ISSUE TITLE
关于label叠加到图像的问题

### ISSUE THREAD

**Issue by SunXusheng5200** [gujingxiao/Lane-Segmentation-Solution-For-Baidu-PaddlePaddle-Autonomous-Driving-Competition#15]
![image](https://user-images.githubusercontent.com/51880608/97825526-e0ddd180-1cf9-11eb-9fdd-6785647a51d3.png)
作者您好！非常感谢您开源了如此优秀的项目。但是当我阅读训练过程的时候，有个trick令我费解，正如图片中所显示的，您在训练过程中将label叠加到图像上，这样会提升训练效果吗，原理是什么呢?

**Comment by gujingxiao** [comment]
你好，第10步是这样的：将label叠加到原图上仅仅是可视化一下结果是否正常，并不是将他叠加到训练中。我是通过结果的叠加发现了像素偏移的问题，然后进行了补偿。

**Comment by SunXusheng5200** [comment]
我明白了，感谢您的解答
