### ISSUE TITLE
Can you share pretrain model ?

### ISSUE THREAD

**Issue by ThorPham** [gujingxiao/Lane-Segmentation-Solution-For-Baidu-PaddlePaddle-Autonomous-Driving-Competition#3]
Can you share pretrain model ? Thank you so much

**Comment by gujingxiao** [comment]
Pretrained Deeplabv3+ has already been released.

**Comment by ThorPham** [comment]
@gujingxiao  I just using your pretrained Deeplabv3+ . But result very bad . Here is some my predict .What's is wrong ?
https://github.com/ThorPham/BAIDU-lane-segmentation
