### ISSUE TITLE
paddle_unet_base - paddle_unet_simple 权重文件

### ISSUE THREAD

**Issue by chenlongsun** [gujingxiao/Lane-Segmentation-Solution-For-Baidu-PaddlePaddle-Autonomous-Driving-Competition#6]
model_weights 
- paddle_unet_base
- paddle_unet_simple
您好，我在跑您的程序，遇到问题，请问这两个权重文件在哪里可以找到？

**Comment by gujingxiao** [comment]
你好，这两个权重由于太大，我并没有上传，仅上传了deeplabV3的权重。所以这两个模型需要你下载数据集自行训练
