### ISSUE TITLE
It seems that the structure of backbone is different from that in the original paper

### ISSUE THREAD

**Issue by songyuc** [gujingxiao/Lane-Segmentation-Solution-For-Baidu-PaddlePaddle-Autonomous-Driving-Competition#7]
Hi, guys,
I am learning about the implementation of DeepLabV3+ these days,
and I find that the structure of backbone is different from that in the original paper.
So what is the reason of modifying the structure of Xception in the model?

Any answer or idea will be appreciated!

**Comment by gujingxiao** [comment]
Hi, sorry for the very late reply.

 I tested original structure and my modified version respectively. To be honest, original one is 2.4% better(COCO Map in segmentation) than mine. However, there are indeed some reasons to make me do some modification. First, my gpus could not afford original structure in such larger resolution, so I must make the net lighter and smaller. Second, the upsampling structure in deeplabV3+ is a little bit simple and would make the result more rough. In this case, I add more layers trying to smooth the lane edge. Last, Balancing the speed and accuracy is always a good reason to try. 

Thanks for your question.
