### ISSUE TITLE
车辆终端部署落地

### ISSUE THREAD

**Issue by yuzhijun2** [gujingxiao/Lane-Segmentation-Solution-For-Baidu-PaddlePaddle-Autonomous-Driving-Competition#8]
您好，请问车道线检测深度模型如何部署在算力较低的嵌入式设备呢

**Comment by gujingxiao** [comment]
> 您好，请问车道线检测深度模型如何部署在算力较低的嵌入式设备呢

可以采用如下几种方式：
１．进行int8甚至int4量化，可以进行提速
２．将工程所用模型的block替换为类似于mobilenet, shufflenet, vovnet, efficientnet等结构，降低计算量
３．可以使用模型剪枝来降低计算量
４．降低输入分辨率

另外你还需要考虑到不同嵌入式平台是否支持这些模型结构．

**Comment by yuzhijun2** [comment]
非常感谢您的指教




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "seigato"<notifications@github.com&gt;; 
发送时间: 2020年5月15日(星期五) 上午10:29
收件人: "gujingxiao/Lane-Segmentation-Solution-For-BaiduAI-Autonomous-Driving-Competition"<Lane-Segmentation-Solution-For-BaiduAI-Autonomous-Driving-Competition@noreply.github.com&gt;; 
抄送: "余智君"<872528229@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gujingxiao/Lane-Segmentation-Solution-For-BaiduAI-Autonomous-Driving-Competition] 车辆终端部署落地 (#8)





  
您好，请问车道线检测深度模型如何部署在算力较低的嵌入式设备呢
  
可以采用如下几种方式：
 １．进行int8甚至int4量化，可以进行提速
 ２．将工程所用模型的block替换为类似于mobilenet, shufflenet, vovnet, efficientnet等结构，降低计算量
 ３．可以使用模型剪枝来降低计算量
 ４．降低输入分辨率
 
另外你还需要考虑到不同嵌入式平台是否支持这些模型结构．
