### ISSUE TITLE
请问如何本项目如何开单机多卡训练？

### ISSUE THREAD

**Issue by pengxiao-song** [gujingxiao/Lane-Segmentation-Solution-For-Baidu-PaddlePaddle-Autonomous-Driving-Competition#9]
显存11g不够用了qaq

**Comment by gujingxiao** [comment]
你好，我测试了一下，训练这里面的模型需要单卡6.8G左右即可，你看一下是不是batch size写的太大了，如果太大的话，改成1吧。另外这个工程有点老了，新的Paddle版本很多接口不一样，在多卡训练方面可能需要做一些调整

**Comment by gujingxiao** [comment]
你好，这个工程当时是为了比赛而写，比赛图片的分辨率是很大的，所以这里写的也很大。如果你使用其他的数据集，是可以把分辨率降低的，在train中修改就可以
